# Generated by Django 5.0.6 on 2024-05-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('이름', models.CharField(max_length=50)),
                ('전화번호', models.CharField(max_length=15)),
                ('이메일', models.EmailField(max_length=254)),
                ('주소', models.CharField(max_length=100)),
                ('생년월일', models.DateField()),
                ('작성자', models.CharField(max_length=200)),
            ],
        ),
    ]
