# Generated by Django 5.0.6 on 2024-05-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonebook',
            name='작성자',
        ),
    ]
